spring.datasource.url: jdbc:h2:file:./camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

server.port: 8091
camunda.bpm.admin-user:
  id: demo
  password: demo
  filter:
    create: All tasks
  license-file: file:///camunda-license.txt
  application.deploy-changed-only: true